import { Providers } from '@/components/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const fontFamily = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
})

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className={fontFamily.variable} lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
